수업/FLASK_AI/DAY03/DBWEB/models/models.py
#--------------------------------------------------------------------------------------
# 데이터 베이스의 테이블 정의 클래스
# -------------------------------------------------------------------------------------- 
# 모듈로딩

from DBWEB import DB




#---------------------------------------------------------------------------------------
# Question 테이블 정의 클래스
#---------------------------------------------------------------------------------------
class Question(DB.Model):
    # 컬럼정의
    id=DB.Column(DB.Integer,primary_key=True)
    subject=DB.Column(DB.String(200),nullable=False)
    content=DB.Column(DB.Text(),nullable=False)
    create_date=DB.Column(DB.DateTime(),nullable=False)

class Answer(DB.Model):
    id=DB.Column(DB.Integer,primary_key=True)
    question_id=DB.Column(DB.Integer,DB.ForeignKey('question.id',ondelete='CASCADE'))
    question=DB.relationship('Question',backref=DB.backref('answer_set',))
    content=DB.Column(DB.Text(),nullable=False)
    create_date=DB.Column(DB.DateTime(),nullable=False)

수업/FLASK_AI/DAY03/DBWEB/__init__.py
#------------------------------------------------------------------------------
#모듈로딩
from flask import Flask

# DB 관련 설정
import config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

DB= SQLAlchemy()
MIGRATE=Migrate()


#-------------------------------------------------------------------------------------
# Application 생성 함수
# - 함수명 : create_app <== 이름변경불가!!
#--------------------------------------------------------------------------------------- 
def create_app():
    # Flask Web Server 인스턴스 생성
    APP=Flask(__name__)

    # DB 관련 초기화 설정
    APP.config.from_object(config)

    # DB 초기화 및 연동
    DB.init_app(APP)
    MIGRATE.init_app(APP,DB)

    # DB 클래스 정의 모듈 로딩
    from .models import models

    # URL 처리 모듈 등록
    from .views import main_view
    from .views import answer_views

    APP.register_blueprint(main_view.mainBP)
    APP.register_blueprint(answer_views.answerBP)

    
    return APP

수업/FLASK_AI/DAY03/DBWEB/views/answer_views.py
from datetime import datetime

from flask import Blueprint,url_for,request
from werkzeug.utils import redirect

from DBWEB import DB
from DBWEB.models.models import Question,Answer

answerBP=Blueprint('answer',__name__,url_prefix='/answer')

@answerBP.route('/create/<int:question_id>',methods=('POST',))
def create(question_id):
    question=Question.query.get_or_404(question_id)
    content=request.form['content']
    answer=Answer(content=content,create_date=datetime.now())
    question.answer_set.append(answer)
    DB.session.commit()
    return redirect(url_for('main.questionItem',question_id=question_id))

수업/FLASK_AI/DAY03/DBWEB/views/main_view.py
#----------------------------------------------------------------------------
# Flask Framework에서 모듈단위 URL 처리 파일
# - 파일명 : main_view.py
# -----------------------------------------------------------------------------
# 모듈로딩
from flask import Blueprint,render_template
from DBWEB.models.models import Question

# Blueprint 인스턴스 생성
mainBP=Blueprint('main',
                 import_name=__name__,
                 url_prefix='/',
                 template_folder='templates')

# http://localhost:5000/ URL처리 라우팅 함수 정의
@mainBP.route('/')
def index():
    return render_template('index.html',name='홍길동')


# http://localhost:5000/qlist URL처리 라우팅 함수 정의
@mainBP.route('/qlist')
def printList():
    ## DB에서 조회한 결과를 HTML 파일로 전달
    q_list=Question.query.all()
    return render_template('question_list.html',question_list=q_list)

# http://localhost:5000/qlist/qdetail/<int:id> URL처리 라우팅 함수 정의
@mainBP.route('/qdetail/<int:question_id>')
def questionItem(question_id):
    ## DB에서 조회한 결과를 HTML 파일로 전달
    q=Question.query.get(question_id)
    return render_template('question_detail.html',question=q)

수업/FLASK_AI/DAY03/DBWEB/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MY WEB</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/style.css')}}"
</head>
<body>
    <h1>Limited Edition</h1>
    {{name}}님 좋은하루 되세요
</body>
</html>

수업/FLASK_AI/DAY03/DBWEB/templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MYWEB</title>
</head>
<body>
    <h1>질문상세보기</h1>
    <div id="quesiton">
        <label>제목:</label>
        {{question.subject}}
        <br><br>
        
        <label>내용:</label>
        {{question.content}}
        <br>
    </div>
    <h5>{{question.answer_set|length}}개의 답변이 있습니다.</h5>
    <div>
        <ul>
            {% for answer in question.answer_set %}
                <li>{{answer.content}}</li>
            {%endfor%}
        </ul>
    </div>
    <div>
        <form action="{{url_for('answer.create',question_id=question.id)}}" method="POST">
            <textarea name='content' rows="5" cols="20" placeholder="답변입력"></textarea>
            <input type="submit" value="답변등록">
        </form>
    </div>
</body>
</html>

수업/FLASK_AI/DAY03/DBWEB/templates/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!--테이블 형식으로 표현-->
    <h1>질문 게시판</h1>
    <table border="1">
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>날짜</th>
        </tr>
        {% if question_list %}
            {% for question in question_list %}    
        <tr>
            
            <td>{{question.id}}</td>
            <td><a href='{{url_for("main.questionItem",question_id=question.id)}}'>{{question.subject}}</a></td>
            <td>{{question.create_date}}</td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="3" class="msg">등록된 질문이 없습니다.</td>
        </tr>
    {% endif %}
    </table>

    <br><br>
    <!--리스트 형식으로 표현-->

    {% if question_list %}
    <ol>
        {% for question in question_list %}
            <li>{{question.subject}}/{{question.content}}</li>
            
        {% endfor %}
    </ol>

    {% else %}
        <p colspan="3" class="msg">등록된 질문이 없습니다.</p>

    {% endif %}

    

</body>
</html>